DROP TABLE IF EXISTS TODO;
DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS TODO (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    todo TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO TODO (todo) VALUES ('Buy milk');
INSERT INTO TODO (todo) VALUES ('Buy eggs');
INSERT INTO TODO (todo) VALUES ('Buy bread');